sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_e5bf5217175a_key -iv $encrypted_e5bf5217175a_iv -in cloud-service.json.enc -out cloud-service.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
